[package]
name = "p2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

criterion = "0.4.0"


[[bench]]
name = "bench"
harness = false

[lib]
name = "p2"
path = "src/lib.rs"
